lista = [
    "Jarawara/Jamamadi/Kanamati", "Kaxarari", "Barreira da Missão", "Igarapé Capana", "Banawá", 
    "Kanamari do Rio Juruá", "Mamoadate", "Camadeni", "Anaro", "Alto Tarauacá", 
    "Kampa e Isolados do Rio Envira", "Kulina Igarapé do Pau", "Karitiana", "Caititu", 
    "Apurinã Km 124 BR-317", "Cacau do Tarauaca", "Bom Intento", "Macarrão", 
    "São Francisco do Canimari", "Kampa do Rio Amônia", "Baú", "Krikati", 
    "Kaxinawá do Rio Jordão", "Jaminawa do Igarapé Preto", "Kaxinawá Colônia Vinte e Sete", "Guanabara", 
    "Jurubaxi-téa", "Mapari", "Peneri/Tacaquiri", "Évare II", "Igarapé do Caucho", 
    "Kaxinawá Nova Olinda", "Alto Rio Negro", "Espírito Santo", "Jaminaua/Envira", 
    "Kumaru do Lago Ualá", "Camicua", "Igarapé Grande", "Inauini/Teuini", "Hi Merimã", 
    "Igarapé Taboca do Alto Tarauacá", "Barro Alto", "Cabeceira do Rio Acre", "Paumari do Lago Paricá", 
    "Andirá-Marau", "Deni", "Balaio", "Campinas/Katukina", "Kaxinawá Ashaninka do Rio Breu", 
    "Água Preta/Inari", "Kaxinawá do Baixo Rio Jordão", "Guajahã", "Ananás", "Sapotal", 
    "Paraná do Arauató", "São Pedro do Sepatini", "Santana", "Igarapé Lage", "Kaxinawá do Rio Humaitá", 
    "Mãe Maria", "Krenyê", "Kampa do Igarapé Primavera", "Badjonkore", "Jaminawa Arara do Rio Bagé", 
    "Kaxinawá da Praia do Carapanã", "Alto Rio Purus", "Acapuri de Cima", "Betania", "Rio Guaporé", 
    "Cuiu-Cuiu", "Catipari/Mamoria", "Lauro Sodré", "Boca do Acre", "Apurinã do Igarapé Mucuim", 
    "Juma", "Igarapé Ribeirão", "Kulina do Medio Jurua", "Estrela da Paz", "Arara do Igarapé Humaitá", 
    "Kulina do Rio Envira", "Évare I", "Karipuna", "Marajai", "Jacareúba/Katauixi (restrição uso)", 
    "Kaxinawá Seringal Independência", "Matintin", "Acimã", "Cué Cué/ Marabitanas", "Mawetek", "Alto Sepatini", 
    "Apiaka/Kayabi", "Arara da Volta Grande do Xingu", "Apiaká do Pontal e Isolados", "Katukina/Kaxinawá", "Miratu", 
    "Lago do Correio", "Jaquiri", "Paumari do Rio Ituxi", "Arara do Rio Amônia", "Paracuhuba", "Tuwa Apekuokawera", 
    "Jumina", "Tikuna de Santo Antonio", "Nova Jacundá", "Estivadinho", "Apurinã Igarapé Tauamirim", "Juruna do Km 17", 
    "Fortaleza do Castanho", "Capoto/Jarina", "Jauary", "Nhamundá/Mapuera", "Uru-Eu-Wau-Wau", "Santa Cruz da Nova Aliança", 
    "Pium", "Aripuanã", "Uirapuru", "Wedezé", "Turé/Mariquita", "Itaitinga", "Taego Ãwa", "Parabubure", "Meria", 
    "Trincheira Bacaja", "Nambikwara", "Vale do Guaporé", "Muriru", "Cunhã-Sapucaia", "Jarudore", "Ponte de Pedra", 
    "Alto Rio Guamá", "Aningal", "Rio Paru DEste", "Menkragnoti", "Porquinhos", "Serra Morena", "Bacurizinho", 
    "Cachoeira Seca", "Anambé", "Barreirinha", "Tumiã", "Setemã", "Fortaleza do Patauá", "Paquiçamba", "Maraitá", 
    "Massaco", "Boqueirão", "Apyterewa", "Sawré Muybu (Pimental)", "Recreio/São Félix", "Wawi", "Cuia", 
    "Kaxuyana-Tunayana", "Tapirapé/Karajá", "Trocará", "Ariramba", "Cobra Grande", "Rio Negro Ocaia", 
    "Arara", "Rio Gregório", "Parakanã", "Parque do Araguaia", "Nova Esperança do Rio Jandiatuba", 
    "Ponta da Serra", "Médio Rio Negro I", "Murutinga/Tracaja", "Tukuna Umariaçu", "Tenharim Marmelos", 
    "Canauanim", "Maraiwatsede", "Parana do Paricá", "Parana do Boa Boa", "Krenrehé", "Urucu/Juruá", 
    "Sangradouro/Volta Grande", "Karajá de Aruanã II", "Morro Branco", "Lagoa dos Brincos", 
    "Cana Brava/Guajajara", "Médio Rio Negro II", "Riozinho", "Rio Gregório", "Tupã-Supé", "Rio Branco", 
    "Merure", "Porquinhos dos Canela-Apãnjekra", "Erikpatsá", "Panará", "Bakairi", "Apurinã do Igarapé São João", 
    "Sururuá", "Uty-Xunaty", "Vista Alegre", "Mangueira", "Cacique Fontoura", "Boa Vista - AM", "Lago do Beruri", 
    "Chão Preto", "Perigara", "Parque do Xingu", "Igarapé Lourdes", "Piripkura (restrição de uso)", "Paresi", 
    "Coata-Laranjal", "Bom Jesus", "Paumari do Lago Marahã", "Estação Parecis", "Rio Biá", "Menkü", "Tubarão Latunde", 
    "São Marcos - RR", "Sepoti", "Tereza Cristina", "Umutina", "Tikúna de Feijoal", "Kayapó", "Yanomami", "Paquiçamba", 
    "Amanayé", "Marechal Rondon", "Lago do Marinheiro", "Moskow", "Raposa Serra do Sol", "Rio Negro Ocaia", "Pirititi", 
    "Nove de Janeiro", "Caru", "Inawebohona", "Sucuba", "Torá", "Serra da Moça", "Xipaya", "Trocará - Doação", 
    "Sissaíma", "Rio Mequens", "Rio Apaporis", "Guató", "Maracaxi", "São Domingos - MT", "Pacaas Novas", "Juininha", 
    "Awa", "Pimentel Barbosa", "Araweté Igarapé Ipixuna", "Lago Jauari", "Manoa/Pium", "Sete de Setembro", 
    "Kraolandia", "Krahó-Kanela", "Uneiuxi", "São Marcos - MT", "Kanela", "Xambioá", "Xerente", "Bragança-Marituba", 
    "Bacurizinho", "Tabalascada", "Utiariti", "Galibi", "Pirineus de Souza", "Malacacheta", "Lagoa Comprida", 
    "Paumari do Cuniua", "Gavião", "Poyanawa", "Arary", "Koatinemo", "Rio Omerê", "Truaru", "Diahui", "Prosperidade", 
    "Ubawawe", "Pinatuba", "Portal do Encantado", "Tukuna Porto Espiritual", "Waiãpi", "Miguel/Josefa", "Sararé", 
    "Rio Jumas", "Arara do Rio Branco", "Rodeador", "Anta", "Praia do Mangue", "Rio Formoso", "Praia do Índio", 
    "Karajá de Aruanã III", "Santa Inez", "Munduruku", "Baía dos Guató", "Tembé", "Paumari do Lago Manissuã", 
    "Turé/Mariquita II", "Maraã Urubaxi", "Kawahiva do Rio Pardo", "Pequizal", "Maró", "Enawenê-Nawê", "Las Casas", 
    "Cajueiro", "Jatuarana", "Lago Capanã", "Vale do Guaporé", "Apinayé", "Itixi Mitari", "Parque do Tumucumaque", 
    "Japuira", "Sai-Cinza", "São Sebastião", "Jacamim", "Alto Turiaçu", "Barata Livramento", "Vui-Uata-In", "Manoki", 
    "Natal/Felicidade", "Ilha do Camaleão", "Kayabi", "Tabocal", "Sagarana", "Tirecatinga", "Waimiri-Atroari", 
    "WaiWái", "Trombetas/Mapuera", "Terena Gleba Iriri", "Kwazá do Rio São Pedro", "Zuruahã", "Maranduba", "Lago do Limão", 
    "Uneiuxi", "Araçá", "Zoró", "Kuruáya", "Tadarimana", "Karajá Santana do Araguaia", "Batovi", "Rio Urubu", "Pirahã", 
    "Munduruku-Taquara", "Roosevelt", "São Leopoldo", "Governador", "Sarauá", "Tanaru (restrição de uso)", "Sororó", 
    "Geralda Toco Preto", "Menkü", "Zoe", "Irantxe", "Rio Téa", "Apipica", "Porto Limoeiro", "Xikrin do Rio Catete", 
    "Figueiras", "Riozinho do Alto Envira", "Lago Aiapua", "Ouro", "Utaria Wyhyna/Iròdu Iràna", "Rio Manicoré", 
    "Uati-Paraná", "Funil", "Batelão", "Patauá", "Nukini", "Porto Praia", "Raimundão", "Kanela Memortumré", "Ipixuna", 
    "Uaçá", "São Pedro", "Ituna/Itatá (restrição de uso)", "Arariboia", "Rio Pindaré", "Areões", "Kararaô", 
    "São Domingos do Jacapari e Estação", "Pequizal do Naruvôtu", "Jabuti", "Padre", "Parque do Aripuanã", "Ponciano", 
    "Cajuhiri Atravessado", "Paukalirajausu", "Seruini/Mariene", "Escondido", "Trincheira", "Tenharim Marmelos (Gleba B)", 
    "Urubu Branco", "Taihantesu", "Tenharim do Igarapé Preto"
]


lista.sort()
lista.insert(0, "Todos")
